#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# find available space
new_member_stat = `ssh -o StrictHostKeyChecking=no #{payload[:member][:local_ip]} stat -f --format=\\\"%a %S\\\" /data/var/db/redis`
available_space = new_member_stat.split(' ')[0].to_i * new_member_stat.split(' ')[1].to_i

# find needed space
needed_space = `du -bs /data/var/db/redis`.split(' ')[0].to_i

if available_space < needed_space
  puts "Receiving side too small!!"
  exit 1
end #unless payload[:clear_data] == "false"


# issue save to the local redis
# 'save' rather than 'bgsave' so it blocks
execute 'execute save' do
  command '/data/bin/redis-cli save'
end

execute "send bulk data to new member" do
  command "tar -cf - /data/var/db/redis | ssh -o StrictHostKeyChecking=no #{payload[:member][:local_ip]} tar -C / -xpf -"
end