#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

if payload[:member][:type] == 'arbitrator'
  service "flip" do
    action :disable
    init :runit
  end

  service "sentinel" do
    action :disable
    init :runit
  end

  file '/etc/nanoinit.d/mroute' do
    action :delete
  end

  directory '/etc/service/flip' do
    action :delete
  end

  directory '/etc/service/sentinel' do
    action :delete
  end
end