#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

execute "/data/bin/redis-cli -p 6380 save"

# TODO: assuming we can scp backups to a backup container
execute "send data to backup container" do
  command <<-EOF
    bash -c 'gzip -c /data/var/db/redis/dump.rdb \
      | tee >(md5sum | cut -f1 -d" " > /tmp/md5sum) \
      | ssh \
      -o StrictHostKeyChecking=no \
      #{payload[:backup][:local_ip]} \
      "cat > /data/var/db/redis/#{payload[:backup][:backup_id]}.gz"
    for i in ${PIPESTATUS[@]}; do
      if [[ $i -ne 0 ]]; then
        exit $i
      fi
    done
    '
  EOF
end

remote_sum = `ssh -o StrictHostKeyChecking=no #{payload[:backup][:local_ip]} "md5sum /data/var/db/redis/#{payload[:backup][:backup_id]}.gz"`.to_s.strip.split(' ').first

# Read POST results
local_sum = File.open('/tmp/md5sum') {|f| f.readline}.strip

# Ensure checksum match
if remote_sum != local_sum
  puts 'checksum mismatch'
  exit 1
end
