#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

execute "retrieve data from backup container" do
  command <<-EOF
    ssh -o StrictHostKeyChecking=no #{payload[:warehouse][:host]} \
    'cat /data/var/db/redis/#{payload[:warehouse][:backup_id]}.gz' \
      | gunzip \
      > /dump.rdb.tmp
  EOF
end

# forced 'appendonly no'
execute 'clean data dir from failed saves' do
  command 'rm -rf /data/var/db/redis/temp*.rdb'
end

execute 'flush redis' do
  command '/data/bin/redis-cli flushall'
end

# TODO: requires `pip install rdbtools`
execute 'replay dump to redis' do
  command '/data/bin/rdb --command protocol /dump.rdb.tmp | /data/bin/redis-cli --pipe'
end

execute 'cleanup dump' do
  command 'rm -f /dump.rdb.tmp'
end
