#!/usr/bin/env bash

cat >/tmp/dump.rdb.tmp

rm -rf /data/var/db/redis/temp*.rdb

/data/bin/redis-cli flushall

/data/bin/rdb --command protocol /tmp/dump.rdb.tmp | /data/bin/redis-cli --pipe

rm -f /tmp/dump.rdb.tmp
