#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# Import service (and start)
directory '/etc/service/cache' do
  recursive true
end

directory '/etc/service/cache/log' do
  recursive true
end

template '/etc/service/cache/log/run' do
  mode 0755
  source 'log-run.erb'
  variables ({ svc: "cache" })
end

template '/etc/service/cache/run' do
  mode 0755
  variables ({ exec: "redis-server /data/etc/redis/redis.conf 2>&1" })
end

sleep 5

service "cache" do
  action :enable
end

ensure_socket 'cache' do
  port '6379'
  action :listening
end

# Attach the IP if provided
if payload[:ips]
  # set up persistance
  file "/etc/nanoinit.d/eth00" do
    content <<-EOF
      ifconfig eth0:0 #{payload[:ips][:default]}
    EOF
    mode 0755
  end

  # bring up interface
  execute "bring up vip" do
    command <<-EOF
      ifconfig eth0:0 #{payload[:ips][:default]}
    EOF
  end
end
